### ISSUE TITLE
Ctrl+Tab problem

### ISSUE THREAD

**Issue by pakosel** [smcpeak/vscode-default-keys-windows#1] opened 2020-05-16 14:28 UTC
Thanks for this great extension, you saved my life! :)
The only issue I have is with Ctrl+Tab and Ctrl+Shift+Tab. After installing the extension it seems like they are not working anymore.
I finally managed to make them work by re-assigning Ctrl+Tab **only** to:
```
{
  "key": "ctrl+tab",
  "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"
}
```
but after this when editor group pops-up I can only go between the items using Ctrl+Shift+Tab (probably because it's bound to the `workbench.action.quickOpenNavigatePreviousInEditorPicker`)

Is there any way to overcome this problem so pressing Ctrl+Tab iterates over opened editors in the cycle? Thanks

**Comment by pakosel** [comment] 2020-05-16 20:21
OK I figured out that adding the following entry in `keybindings.json` fix this issue:
```
{
    "key": "ctrl+tab",
    "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
}
```
Tested on two of my Linux machines and it does the job

**Comment by smcpeak** [comment] 2020-05-17 01:55
Thanks for reporting this and figuring out a solution.  I haven't investigated the issue myself, only read what you wrote.  I see you closed the issue, but is there something I could add to the extension that would avoid others running into the same problem?

**Comment by pakosel** [comment] 2020-05-17 16:47
> Thanks for reporting this and figuring out a solution. I haven't investigated the issue myself, only read what you wrote. I see you closed the issue, but is there something I could add to the extension that would avoid others running into the same problem?

Just created a pull request that should fix the issue. Tested locally and works fine

**Comment by smcpeak** [comment] 2020-05-18 10:33
Reopening as I investigate problem and proposed solution.

**Comment by smcpeak** [comment] 2020-05-18 10:39
After investigation, I determined that the problem with Ctrl+Tab was caused by the default binding command changing from workbench.action.openNextRecentlyUsedEditorInGroup to workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup somewhere between VSCode 1.41.1 and VSCode 1.45.1.  Removing the former binding as proposed in the PR fixed the issue with this key, but not quite in the way I would like, and leaves a bunch of other bindings referring to commands that no longer exist.

In a3b7a92 I instead refreshed all of the bindings to match the defaults for VSCode 1.45.1, which fixes the problem with Ctrl+Tab and the rest.

I have uploaded the new version 0.0.5 to the marketplace as well as published it as a release on Github.  With that, I am re-closing.

**Closed by smcpeak** 2020-05-18 10:39 UTC
